language: ruby
rvm:
- 2.3.3
before_install:
- cd site
- nvm install 7
- npm install
script:
- npm run build
- npm run precache
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
env:
  global:
    secure: Qc+CfjHvJr9pGAUBw6jKWfpLvRzpSK+nQ19qYqaHwHnSYYh/tFA5gY6oQKBD02UutmBzn0v2qHyPtEKbLwXcicNcz8Wo9TN+LrLy45jIinglbDkeeT0d4B4J8IKuM2rx+kuVavzFfYeUWTaLLZ3PHFMtpUj517VyNmjNeGx8lfhOqzyQJJQ+Xy4mwrr19yRSYH9jpDEuLbHCFnTK/zt88Xu5JOirJTOHiitWo5/nJf/DjoMXJV4eNVECX9y8BVPmfY70Q9kljEw93uUU63dk1rITvTh0N2bGjz4EA7pyF+x7A0/8EtzF52D3GbodHuuHmxIPO0/jDho3goy/XzKrwP85CWOsjMxT08OfjoEOvLtrPE2dUQmtR7uuAkphsv+RnlA7wNDJuWtLM/1cMoQNiuwanKOfLsZ/SLwVIFudPBPjkAT+vNE45RWWpPBhrt33S6DSTyFBsachumpmtAteAIjOekGOZykfmtiN2Qk5zkPmqKHp7FH/VzVY9XwcXOTCUU6rDjBUOC7lEVb8gXd2dWnTEqu3jtXsJ6r8g8Wy7afWHsVWHH9zwVoXD4xjuIy/qMAp07TWwQjj3omESJgH78rWyvczpa5XHlJKvfUtvLg3ONxnnhFAYoY8zNUH8REMqqVRc3AqAAkI8Rrgu3AUz8yINVJCeCFDTRbiMwADXQU=
