language: ruby
rvm:
- 2.3.3
before_install:
- cd site
- nvm install 7
- npm install
# Cloud Functions has its own package.json 
- cd functions && npm i && cd ..
script:
- npm run build
- npm run precache
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
env:
  global:
    secure: k1fUHvLf3YawrS9M3rCzaS8xlt9F7s33UtuDFcFCpEQP02FYRos/shmlAgJ6MCzdRfVxNAeJ4f8skmygaKZoNdvqi6l8zZGQhSRc5SeWDLtZe3u5gUS9l7uUUgPLpHz7KXhPTie0FU2sbRRvqpOno8zXsR5ysggwHPShhx6aaVES8aOSsyWduPClewTNHnUEV5O8lMoyUPFJWe4zPF2IlKci5lE8tUddZyi+ue3pwuoBs+0ITKVRxxX9LIS3Ktu5MKAIWB2DC/zZ3TisL9eaGrHutkvYdF7CrndbQ7Vp/5QXfrvq+7e1A7ui39jvd0QdPu8W7xuxmOIJ/8rApmVJ/8jZW//g4YJTj4D1AIbbcocCLHZXO8Lg9OCLgOmyUJP0qH1z0JwHvBQCaDrJWIJxybPGZueDfmee2Sz1ZtpgyYfv4MfQthYOaOc7VKqK9NgJs2U+mjBQWr4p3aS57FAmsTBU/VbpdaXqHK+lH398rAopGWOjT+wt5bJzPpO1hiFObrJSIthnxH4WNRyrLxs3JZ8iCrMDOiF1Kv+/DyeoevaHLcNpsTqodJ+UpxAPPpoWxbKE7J95ntFul+KuMbZYNoG/4HUTDlCjvpJbOqJKCrX2PmKMABA4/mfBoLEjVoCu25gNmAve3auqvJnuZ3w1AFbewPx8fNdVbBAX7vQ6zxo=
