---
runtime: go
api_version: go1
default_expiration: 300s

handlers:
- url: /
  static_files: _site/index.html
  upload: _site/index\.html
  http_headers:
    X-UA-Compatible: "IE=edge"

- url: /(.*)
  static_files: _site/\1
  upload: _site/(.*)

skip_files:
- ^_apps
- ^_contributors
- ^_includes
- ^_layouts
- ^_sass
- ^assets
- ^node_modules
- ^_config\.yml$
- ^Gemfile.*
- ^package\.json$
- ^sw-precache-config\.js$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.gpg$

- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
